/**
 * Self-host stack control (Mode B).
 *
 * Drives `docker compose` for services/selfhost — relay + LiveKit + Ollama — so
 * "run it yourself" is a button rather than a terminal session.
 *
 * The packaged app has no repo checkout, so the stack is *materialized* into
 * userData on first start: compose file, LiveKit config, and the relay source
 * (compose builds the relay image from it). Keeping it in userData rather than
 * resources also means the generated .env — which holds the LiveKit secret — is
 * somewhere writable and per-user.
 */
import { app, ipcMain } from "electron";
import { execFile } from "node:child_process";
import { randomBytes } from "node:crypto";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

export interface StackService {
  name: string;
  state: string;
  running: boolean;
}
export interface StackStatus {
  /** Docker CLI + compose plugin both present. Everything else needs this. */
  dockerAvailable: boolean;
  /** Docker is installed but the daemon isn't accepting connections. */
  daemonRunning: boolean;
  services: StackService[];
  /** True when every service in the project is up. */
  running: boolean;
  /** Client-reachable relay URL once up, for one-click "use this relay". */
  relayUrl: string;
  error?: string;
}

const STACK_DIR = () => join(app.getPath("userData"), "umbry-stack");
const COMPOSE_DIR = () => join(STACK_DIR(), "selfhost");

/** Where the shipped stack templates live (resources when packaged, repo in dev). */
function templateRoot(): string {
  return app.isPackaged
    ? join(process.resourcesPath, "stack")
    : join(app.getAppPath(), "..", "..", "services");
}

function run(
  cmd: string,
  args: string[],
  opts: { cwd?: string; timeoutMs?: number } = {},
): Promise<{ ok: boolean; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile(
      cmd,
      args,
      { cwd: opts.cwd, timeout: opts.timeoutMs ?? 20_000, windowsHide: true, maxBuffer: 8 * 1024 * 1024 },
      (err, stdout, stderr) => {
        resolve({ ok: !err, stdout: String(stdout ?? ""), stderr: String(stderr ?? "") });
      },
    );
  });
}

/** `docker compose` (v2 plugin) — the only form we support; v1 `docker-compose` is EOL. */
async function compose(args: string[], timeoutMs?: number) {
  return run("docker", ["compose", ...args], { cwd: COMPOSE_DIR(), timeoutMs });
}

async function copyIfMissing(from: string, to: string) {
  if (existsSync(to)) return;
  if (!existsSync(from)) throw new Error(`stack template missing: ${from}`);
  await copyFile(from, to);
}

/**
 * Lay the stack down in userData. Idempotent: existing files (notably .env,
 * which carries the user's LiveKit secret and host choice) are never clobbered.
 */
async function materialize(): Promise<void> {
  const src = templateRoot();
  const composeDir = COMPOSE_DIR();
  const relayDir = join(STACK_DIR(), "relay");
  await mkdir(composeDir, { recursive: true });
  await mkdir(relayDir, { recursive: true });

  await copyIfMissing(join(src, "selfhost", "docker-compose.yml"), join(composeDir, "docker-compose.yml"));
  await copyIfMissing(join(src, "selfhost", "livekit.yaml"), join(composeDir, "livekit.yaml"));
  // compose builds the relay image from `context: ../relay`.
  for (const f of ["Dockerfile", "package.json", "server.mjs"]) {
    await copyIfMissing(join(src, "relay", f), join(relayDir, f));
  }

  const envPath = join(composeDir, ".env");
  if (!existsSync(envPath)) {
    // Fresh credentials per install — never a shipped default secret.
    const key = randomBytes(16).toString("hex");
    const secret = randomBytes(32).toString("hex");
    await writeFile(
      envPath,
      [
        "# Generated by Umbry on first stack start. Safe to edit.",
        "# UMBRY_HOST is the address CLIENTS use — change to your LAN IP to let",
        "# teammates connect, otherwise calls will fail for them.",
        "UMBRY_HOST=localhost",
        `LIVEKIT_API_KEY=${key}`,
        `LIVEKIT_API_SECRET=${secret}`,
        "AI_MODEL=qwen2.5:7b",
        "CORS_ORIGIN=*",
        "RELAY_REQUIRE_AUTH=1",
        "RELAY_PORT=8788",
        "LIVEKIT_PORT=7880",
        "",
      ].join("\n"),
      "utf8",
    );
  }
}

async function readEnvValue(key: string, fallback: string): Promise<string> {
  try {
    const txt = await readFile(join(COMPOSE_DIR(), ".env"), "utf8");
    const m = txt.match(new RegExp(`^${key}=(.*)$`, "m"));
    return m?.[1]?.trim() || fallback;
  } catch {
    return fallback;
  }
}

async function relayUrl(): Promise<string> {
  const host = await readEnvValue("UMBRY_HOST", "localhost");
  const port = await readEnvValue("RELAY_PORT", "8788");
  return `http://${host}:${port}`;
}

export async function stackStatus(): Promise<StackStatus> {
  const base: StackStatus = {
    dockerAvailable: false,
    daemonRunning: false,
    services: [],
    running: false,
    relayUrl: await relayUrl(),
  };

  const ver = await run("docker", ["compose", "version"], { timeoutMs: 8000 });
  if (!ver.ok) return base;
  base.dockerAvailable = true;

  // `docker info` fails fast when the CLI is installed but the daemon is down
  // (Docker Desktop not launched) — a distinct state worth showing the user.
  const info = await run("docker", ["info", "--format", "{{.ServerVersion}}"], { timeoutMs: 10_000 });
  if (!info.ok) return base;
  base.daemonRunning = true;

  if (!existsSync(join(COMPOSE_DIR(), "docker-compose.yml"))) return base;
  const ps = await compose(["ps", "--format", "json"], 15_000);
  if (!ps.ok) return { ...base, error: ps.stderr.trim().slice(0, 300) };

  // compose emits either NDJSON (one object per line) or a JSON array,
  // depending on version — handle both rather than betting on one.
  const out = ps.stdout.trim();
  let rows: { Service?: string; Name?: string; State?: string }[] = [];
  if (out.startsWith("[")) {
    try {
      rows = JSON.parse(out);
    } catch {
      rows = [];
    }
  } else {
    rows = out
      .split("\n")
      .filter(Boolean)
      .flatMap((l) => {
        try {
          return [JSON.parse(l)];
        } catch {
          return [];
        }
      });
  }

  base.services = rows.map((r) => ({
    name: r.Service ?? r.Name ?? "?",
    state: r.State ?? "unknown",
    running: (r.State ?? "").toLowerCase() === "running",
  }));
  const expected = ["relay", "livekit", "ollama"];
  base.running = expected.every((n) => base.services.some((s) => s.name === n && s.running));
  return base;
}

/**
 * Bring the stack up. The first run builds the relay image and pulls LiveKit +
 * Ollama (hundreds of MB), so this is slow — the caller polls stackStatus()
 * rather than waiting on it.
 */
export async function stackUp(): Promise<StackStatus> {
  await materialize();
  // 15 min: first-run image pulls on a slow connection genuinely take that long.
  const r = await compose(["up", "-d"], 15 * 60_000);
  const status = await stackStatus();
  if (!r.ok && !status.running) {
    return { ...status, error: (r.stderr || r.stdout).trim().slice(0, 500) || "docker compose up failed" };
  }
  return status;
}

export async function stackDown(): Promise<StackStatus> {
  // Containers stop; named volumes (chat history, pulled models) survive, so
  // stopping the stack is never destructive.
  await compose(["down"], 90_000);
  return stackStatus();
}

export function setupSelfHost(): void {
  ipcMain.handle("umbry:stack:status", () => stackStatus());
  ipcMain.handle("umbry:stack:up", () => stackUp());
  ipcMain.handle("umbry:stack:down", () => stackDown());
}
